import {DeleteCategory} from "./category.actions";

export const authConstants ={
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_FAILURE:"LOGIN_FAILURE",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGOUT_REQUEST:"LOGOUT_REQUEST",
}
export const categoryConstants ={
    GET_ALL_CATEGORIES_REQUEST:"GET_ALL_CATEGORIES_REQUEST",
    GET_ALL_CATEGORIES_SUCCESS:" GET_ALL_CATEGORIES_SUCCESS",
    GET_ALL_CATEGORIES_FAILURE:"GET_ALL_CATEGORIES_FAILURE",
    DELETE_CATEGORY_REQUEST:"DELETE_CATEGORY_REQUEST",
    DELETE_CATEGORY_SUCCESS:"DELETE_CATEGORY_SUCCESS",
    DELETE_CATEGORY_FAILURE:"DELETE_CATEGORY_FAILURE",
    ADD_CATEGORY_REQUEST:"ADD_CATEGORY_REQUEST",
    ADD_CATEGORY_SUCCESS:"ADD_CATEGORY_SUCCESS",
    ADD_CATEGORY_FAILURE:"ADD_CATEGORY_FAILURE"
}

export const productContants={
    GET_ALL_PRODUCTS_REQUEST:"GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS:"GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILED:"GET_ALL_PRODUCTS_FAILED",
    ADD_PRODUCTS_REQUEST:"ADD_PRODUCTS_REQUEST",
    ADD_PRODUCTS_SUCCESS:"ADD_PRODUCTS_SUCCESS",
    ADD_PRODUCTS_FAILURE:"ADD_PRODUCTS_FAILURE",
    EDIT_PRODUCT_SUCCESS:"EDIT_PRODUCT_SUCCESS",
    EDIT_PRODUCT_REQUEST:"EDIT_PRODUCT_REQUEST",
    EDIT_PRODUCT_FAILED:"EDIT_PRODUCT_FAILED",
}

export const userConstants={
    GET_ALL_USERS_REQUEST:"GET_ALL_USERS_REQUEST",
    GET_ALL_USERS_SUCCESS:"GET_ALL_USERS_SUCCESS",
    GET_ALL_USERS_FAILED:"GET_ALL_USERS_FAILED",
    EDIT_ALL_USERS_SUCCESS:"EDIT_ALL_USERS_SUCCESS",
    EDIT_ALL_USERS_REQUEST:"EDIT_ALL_USERS_REQUEST",
    EDIT_ALL_USERS_FAILED:"EDIT_ALL_USERS_FAILED"
}